server:
  port: 8781

spring:
  application:
    name: springcloud-demo-gateway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud_demo
    username: root
    password: pass4mysql
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200


eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8181/eureka/
      defaultZone: http://master.eureka.atstudy.top:8181/eureka/,http://slave2.eureka.atstudy.top:8182/eureka/,http://slave3.eureka.atstudy.top:8183/eureka/
  instance:
    instance-id: springcloud-demo-zuul:8781
    prefer-ip-address: true

info:
  app.name: springcloud-demo-zuul
  company.name: www.atstudy.top
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  ignored-services: "*"
  routes:
    consumer.serviceId: springcloud-demo-consumer
    consumer.path: /consumer/**
  prefix: /api