server:
  port: 8381

spring:
  application:
    name: springcloud-demo-consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud_demo
    name: root
    password: pass4mysql
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
