server:
  port: 8981

spring:
  application:
    name: springcloud-demo-rabbitmq-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud_demo
    username: root
    password: pass4mysql
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  rabbitmq:
    username: atstudy
    password: atstudy
    host: 47.93.33.48
    port: 5672


eureka:
  client:
    service-url:
#      defaultZone: http://master.eureka.atstudy.top:8181/eureka/
      defaultZone: http://master.eureka.atstudy.top:8181/eureka/,http://slave2.eureka.atstudy.top:8182/eureka/,http://slave3.eureka.atstudy.top:8183/eureka/

  instance:
    instance-id: springcloud-demo-rabbitmq-client:8981
    prefer-ip-address: true

info:
  app.name: springcloud-demo-rabbitmq-client:8981
  company.name: www.atstudy.top
  build.artifactId: $project.artifactId$
  build.version: $project.version$
